services:
  - type: web
    name: evled-timer
    env: node
    region: oregon
    buildCommand: |
      apt-get update -y && 
      apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev &&
      apt-get install -y zlib1g-dev &&
      npm install &&
      npm run build
    startCommand: npm start
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
    healthCheckPath: /api/health
    staticPublishPath: ./dist